name: interp-planning
channels:
  - defaults
dependencies:
  - python=3.10
  - torchvision==0.19.1
  - pytorch==2.4.1
  - torchaudio==2.4.1
  - ipykernel
prefix: /Users/derekgeng/anaconda3/envs/interp-planning
